config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins, :path => "admin", :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :posts
  post "preview" => Preview
  root :to => "posts#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :trackable, :validatable, :lockable, :timeoutable
  attr_accessible :username, :email, :password, :password_confirmation

  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  validates_presence_of :title, :body
  has_friendly_id :title, :use_slug => true
  acts_as_taggable

  scope :tagged, lambda { |tag| tagged_with(tag) }
  scope :recent, order("created_at desc")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:index, :show]
  respond_to :atom, :only => [:index]

  def index
    @posts = Post.recent.tagged(params[:tag]).paginate(:page => params[:page], :per_page => 5)
    index!
  end

  def create
    @post = Post.new(params[:post])
    @post.admin = current_admin
    create!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Jairo Luiz
      = yield :title
    = raw javascript_include_tag :defaults
    = raw stylesheet_link_tag "screen", :media => "screen, projection"
    = raw stylesheet_link_tag "print", :media => "print"
    /[if lt IE 8]
      = raw stylesheet_link_tag "ie", :media => "screen, projection"
    %link{:href => posts_path(:format => :atom), :rel => "alternate", :type => "application/rss+xml"}
    = csrf_meta_tag
  %body
    #container
      #header= render "shared/header"
      #content= yield
      #sidebar= render "shared/sidebar"
      #footer= render "shared/footer"

app/views/posts/_form.html.haml
= raw javascript_include_tag "markitup"
= raw javascript_include_tag "textile"
= raw javascript_include_tag "posts"
= raw stylesheet_link_tag "markitup"
= raw stylesheet_link_tag "textile"

= simple_form_for @post do |f|
  .field
    = f.input :title, :input_html => { :disabled => readonly }
  .field
    = f.input :body, :input_html => { :class => "mceEditor" }
  .field
    = f.input :tag_list
  .field
    = f.input :published
  .actions
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editing post

= render :partial => "form", :locals => { :readonly => true }

.post_footer
  = link_to "Show", @post
  \|
  = link_to "Back", posts_path

app/views/posts/index.html.haml
- @posts.each do |post|
  - if post.published or admin_signed_in?
    .datebox
      .month= post.created_at.strftime "%b"
      .day= post.created_at.day 
    .title
      = link_to post.title, post
      .date
        on
        = post.created_at.strftime "%B %d, %Y"
    .body
      :preserve
        #{textilize(truncate(post.body, :length => 600))}
    %br
    .post_footer
      By 
      = mail_to post.admin.email, post.admin.username
      \|
      = link_to "Comments", post_path(post, :anchor => "disqus_thread")
      = raw disqus_comment_counts
      \|
      = link_to "Read more", post
      - if admin_signed_in?
        \|
        = link_to "Edit", edit_post_path(post)
        \|
        = link_to "Destroy", post, :confirm => "Are you sure?", :method => :delete

    .tags
      Tags
      - post.tag_list.each do |tag|
        = link_to tag, posts_path(:tag => tag)

  %br
  %hr

.pagination
  = will_paginate @posts

app/views/posts/new.html.haml
%h1 New post

= render :partial => "form", :locals => {:readonly => false}

.post_footer
  = link_to "Back", posts_path

app/views/posts/show.html.haml
- content_for :title do
  = " | #{@post.title}"

.datebox
  .month= @post.created_at.strftime "%b"
  .day= @post.created_at.day 
.title
  = link_to @post.title, @post
  .date
    on
    = @post.created_at.strftime "%B %d, %Y"
.body
  :preserve
    #{textilize(@post.body)}
%br
.post_footer
  By 
  = mail_to @post.admin.email, @post.admin.username
  - if admin_signed_in?
    \|
    = link_to "Edit", edit_post_path(@post)
    \|
    = link_to "Destroy", @post, :confirm => "Are you sure?", :method => :delete

= raw disqus_thread

app/views/shared/_footer.html.haml
.footer
  Simple 
  = link_to "blog", "http://github.com/tangzero/blog"
  application by
  = link_to "tangzero", "http://github.com/tangzero"
  \|
  2010

app/views/shared/_header.html.haml
.fork_me
  = link_to "http://github.com/tangzero/blog" do
    = image_tag "forkme.png"

= link_to root_path do
  .header
    jairo
    %span.color luiz

.slogan
  %span a little of everything that I like

app/views/shared/_sidebar.html.haml
%ul
  %li
    %p Tags
    .tag_cloud
      - tag_cloud(Post.tag_counts, %w(tag1 tag2 tag3 tag4)) do |tag, css_class|
        = link_to tag.name, posts_path(:tag => tag.name), :class => css_class
  %li
    %p Sites
    .sites
      = link_to "http://www.programadorpoliglota.com.br" do
        = image_tag "http://www.programadorpoliglota.com.br/images/programador-poliglota-120x60.gif"
      = link_to "http://github.com/tangzero" do
        = image_tag "http://github.com/images/modules/header/logov3-hover.png", :size => "120x50"